export const types = {
  TWEET_LIST_REQUEST: "TWEET_LIST_REQUEST",
  TWEET_LIST_SUCCESS: "TWEET_LIST_SUCCESS",
  TWEET_LIST_FAILURE: "TWEET_LIST_FAILURE",

  TWEET_DELETE_REQUEST: "TWEET_DELETE_REQUEST",
  TWEET_DELETE_SUCCESS: "TWEET_DELETE_SUCCESS",
  TWEET_DELETE_FAILURE: "TWEET_DELETE_FAILURE",

  TWEET_CREATE_REQUEST: "TWEET_CREATE_REQUEST",
  TWEET_CREATE_SUCCESS: "TWEET_CREATE_SUCCESS",
  TWEET_CREATE_FAILURE: "TWEET_CREATE_FAILURE",

  TWEET_DRAFT: "TWEET_DRAFT",
};

export default types;
